#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Matrix
# This files check if all user configuration requirements are met
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

if ! hass.directory_exists "/config/matrix"; then
    hass.log.info "Config directory at '/config/matrix' does not exist. Creating.."
    mkdir -p /config/matrix
fi

if ! hass.file_exists "/config/matrix/synapse.yaml"; then
    hass.log.info "Config file at '/config/matrix/synapse.yaml' does not exist. Creating.."
    python2 -m synapse.app.homeserver \
        --server-name "hassio" \
        --config-path /data/matrix/synapse.yaml \
        --generate-config \
        --report-stats=no

    mv /data/matrix/synapse.yaml /config/matrix/synapse.yaml

    yq delete --inplace /config/matrix/synapse.yaml 'listeners[1]'
    yq write --inplace /config/matrix/synapse.yaml 'enable_registration' true
    yq write --inplace /config/matrix/synapse.yaml 'database.args.database' /data/matrix.db
    yq write --inplace /config/matrix/synapse.yaml 'media_store_path' /data/matrix/media
    yq write --inplace /config/matrix/synapse.yaml 'uploads_path' /data/matrix/uploads
    yq write --inplace /config/matrix/synapse.yaml 'max_upload_size' '200M'
fi

if hass.config.true 'ssl'; then
    yq write --inplace /config/matrix/synapse.yaml 'no_tls' false
    yq write --inplace /config/matrix/synapse.yaml 'listeners[0].tls' true
    yq write --inplace /config/matrix/synapse.yaml 'tls_certificate_path' /ssl/$(hass.config.get 'certfile')
    yq write --inplace /config/matrix/synapse.yaml 'tls_private_key_path' /ssl/$(hass.config.get 'keyfile')
else
    yq write --inplace /config/matrix/synapse.yaml 'no_tls' true
    yq write --inplace /config/matrix/synapse.yaml 'listeners[0].tls' false
    # Synapse complains if there is not a certificate present even with no_tls set.
    # These are self-signed certificates generated by the above python command.
    yq write --inplace /config/matrix/synapse.yaml 'tls_certificate_path' /data/matrix/hassio.tls.crt
    yq write --inplace /config/matrix/synapse.yaml 'tls_private_key_path' /data/matrix/hassio.tls.key
fi

# Add warning to top of file
sed -i '1s/^/# Make sure you know what you are doing before editing this file!\n/' /config/matrix/synapse.yaml
sed -i '1s/^/# Be aware that this file contains options that could potentially break the addon.\n/' /config/matrix/synapse.yaml
