#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Matrix
# Configures the Matrix Synapse server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare server_name
server_name=$(hass.config.get 'server_name')

if hass.file_exists "/config/matrix.yaml"; then
    declare old_name
    old_name=$(yq read /config/matrix.yaml 'server_name')
    if [[ "$old_name" != "$server_name" ]]; then
        hass.log.fatal "The server_name has changed!"
        hass.log.fatal "Are you sure you want to do this?"
        hass.log.fatal "If so, delete the 'matrix.yaml' file located in '/config' and restart the addon."
        hass.die "WARNING: This will remove all rooms, users, chats and start afresh."
    fi
fi

if ! hass.file_exists "/config/matrix.yaml"; then
    hass.log.info "Config file at '/config/matrix.yaml' does not exist. Creating.."

    rm -f /share/matrix/matrix.db

    python3.6 -m synapse.app.homeserver \
        --server-name "$server_name" \
        --config-path /data/matrix/matrix.yaml \
        --generate-config \
        --report-stats=no

    mv /data/matrix/matrix.yaml /config/matrix.yaml

    yq delete --inplace /config/matrix.yaml 'listeners[1]'
    yq write --inplace /config/matrix.yaml 'enable_registration' true
    yq write --inplace /config/matrix.yaml 'database.args.database' '/share/matrix/matrix.db'
    yq write --inplace /config/matrix.yaml 'media_store_path' '/share/matrix/media'
    yq write --inplace /config/matrix.yaml 'uploads_path' '/share/matrix/uploads'
    yq write --inplace /config/matrix.yaml 'max_upload_size' '200M'
fi

if hass.config.true 'ssl'; then
    yq write --inplace /config/matrix.yaml 'no_tls' false
    yq write --inplace /config/matrix.yaml 'listeners[0].tls' true
    yq write --inplace /config/matrix.yaml 'tls_certificate_path' "/ssl/$(hass.config.get 'certfile')"
    yq write --inplace /config/matrix.yaml 'tls_private_key_path' "/ssl/$(hass.config.get 'keyfile')"
else
    yq write --inplace /config/matrix.yaml 'no_tls' true
    yq write --inplace /config/matrix.yaml 'listeners[0].tls' false
    # Synapse complains if there is not a certificate present even with no_tls set.
    # These are self-signed certificates generated by the above python command.
    yq write --inplace /config/matrix.yaml 'tls_certificate_path' "/data/matrix/$server_name.tls.crt"
    yq write --inplace /config/matrix.yaml 'tls_private_key_path' "/data/matrix/$server_name.tls.key"
fi

# Add warning to top of file
sed -i '1s/^/# Make sure you know what you are doing before editing this file!\n/' /config/matrix.yaml
sed -i '1s/^/# Be aware that this file contains options that could potentially break the addon.\n/' /config/matrix.yaml
